# Use the official PHP image as the base image
FROM php:8.1-fpm

# Install MySQL extensions
RUN docker-php-ext-install pdo_mysql mysqli

# Add any additional configurations or dependencies if needed

# Set the working directory
WORKDIR /var/www


